### ISSUE TITLE
Get ready for Leaflet 1.0

### ISSUE THREAD

**Issue by simison** [tombatossals/angular-leaflet-directive#851]
http://leafletjs.com/2015/07/15/leaflet-1.0-beta1-released.html

>The release sports a number of minor breaking API changes, and some of the plugins will have to be updated. To make the upgrade less painful, we’re doing a short beta cycle before the final 1.0 to allow users and plugin developers to catch up to the changes while we find and fix remaining issues.

:-)

**Comment by tombatossals** [comment]
Wow, great news. That would be a good moment for giving this directive a power up.

Thanks for reporting!

**Comment by paambaati** [comment]
@tombatossals Is there a branch for this that we could check out/test/conribute?

**Comment by nmccready** [comment]
Referencing Mobile Draw Support . IE: This is another reason to get started on this.
https://github.com/Wildhoney/Leaflet.FreeDraw/issues/3

**Comment by nmccready** [comment]
I will be adding a leaflet 1.0.X branch to start working towards this. However I am not sure what the name of the branch should be.

leaflet-1.0.X to targets leaflet? Or just 1.0.X as we are working towards a 1.0.X ourselves. 

My only beef with making it 1.0.X is that going to leaflet 1.0.X might not be stable right away. But keeping the branch with 1.0.X and mapping to leaflet 1.0.X helps eliminate confusion.

Thoughts anyone?

**Comment by vrubert** [comment]
Looks good @nmccready, I think too we need that branch because it will need some time to have the directive working with leaflet 1.0.x and all the modules.

BTW, the Leaflet.FreeDraw project is amazing!!

**Comment by nmccready** [comment]
@vrubert @tombatossals any thoughts on what you want the branch name to be?

**Comment by simison** [comment]
Keeping the future version number of this package at the branch name makes more sense to me rather than following Leaflet versions. 

I'd call it "1.0.0-with-leaflet-1.x", "1.0.0-WIP" or just "1.0.0"

**Comment by tombatossals** [comment]
Hey, I would suggest  "1.0.0-wip" as @simison said, what do you think?

I haven't had time to take a look at leaflet-1.0-beta, I expect there will be no major API changes and 90% will work seamlessly. I hope so.

**Comment by nmccready** [comment]
Awesome I hope so too, what is WIP? Work In Progress? I am not sure if that is needed as all branches are WIP :grinning:  .

**Comment by nmccready** [comment]
Or is it WLP?

**Comment by nmccready** [comment]
hmm maybe just leaflet-1.X

**Comment by nmccready** [comment]
That way if we have any major changes (unseen foreseeable) we don't need to rename the branch.

**Comment by tombatossals** [comment]
You're right, all branches are WIP :D 

Totally agree, better leaflet-1.X so no need to rename it later.

**Comment by nmccready** [comment]
cool I'll push the branch up

**Comment by simison** [comment]
WIP suggests that it's currently in progress and shouldn't be expected to work. ;-)

leaflet-1.x is cool tho. Thanks for working on it!

**Comment by nmccready** [comment]
Working on this, and I can not find the leaflet-src.js dist file for master or 1.0.0-beta1

**Comment by nmccready** [comment]
See https://github.com/Leaflet/Leaflet/issues/3635

**Comment by nmccready** [comment]
Good lord, they made it incompatible with bower.. ie it is not standardized anymore. 

https://github.com/Leaflet/Leaflet/issues/1354

**Comment by nmccready** [comment]
Ok, so far we have a few alternatives

- bower will point to `"leaflet": "http://cdn.leafletjs.com/downloads/leaflet-1.0.0-b1.zip"` . The big problem with this is that it makes our library and leaflet dependencies an invalid mess where version number really means nothing.

- become a npm project and abandon bower

- fork leaflet to get the tags to have `dist/*.js` files again

This is a real problem with a lot of future headache. It would be nice

**Comment by simison** [comment]
Hmm, nope, they do have dist files for releases. (https://github.com/Leaflet/Leaflet/issues/3635#issuecomment-125168272)

It's just this beta which is lacking those files (https://github.com/Leaflet/Leaflet/issues/3635#issuecomment-123267747); it'll be fixed with the next version.

For WIP using the beta-1 zip path is fine.

**Comment by nmccready** [comment]
Yeah they need to do another release. However this still doesn't make me that confident in bower as a solution. This will probably be a headache in the future for sure. I vote for becoming npm centric.

**Comment by nmccready** [comment]
This brings up a good discussion though. It would be nice to not always be committing dist/*.js as it would keep the PR size very small and easier to review. I wonder if we should start doing something similar and only publish dist/*.js on tags/releases. Alternatively we could have a dist repo. Ugh.. all more work I don't feel like doing.

**Comment by nmccready** [comment]
With the `dist/*.js` ignored solution; this would only mess with people that target master. This would be tons of plunkers and many users.

**Comment by nmccready** [comment]
All the branch exists on the main repo. Feel free to start making the specs work. On a positive note the 604 example appears to work at least partially.

**Comment by simison** [comment]
Bower will eventually die out as NPM evolves, I suppose. Anyway, for this sort of package it's very important to stay distribution channel agnostic and just keep supporting everything that's feasible. Bower is still hugely popular for good reasons.

Having a CI script to produce dist files sounds totally something this package should have. :-) Have a look at Leaflet's build scripts?

**Comment by nmccready** [comment]
There scripts are all using jake, I would prefer to look at grunt or gulp as I do not feel like learning another tool just for another tool sake.

**Comment by nmccready** [comment]
If someone wants to take that work on by all means go for it. I am not nominating myself at all for a dist repo. However, I can support bower still if it is desired. But I think we need to better support npm. Also ti would be nice to have privileges to push to npm as only @tombatossals has that right now.

**Comment by simison** [comment]
+1 for better support npm

**Comment by alexkavon** [comment]
If bower support disappears, then ALOT of mobile ionic apps will stop working, best to support both until one consumes the other.

**Comment by nmccready** [comment]
It looks like leaflet is back on board with bower for now so we should be ok with both.

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
